name: e_store
description: A client e-store app.
publish_to: 'none'
version: 1.0.0-Cinnamon

environment:
  sdk: '>=3.1.5 <4.0.0'

# ------------ Dependencies ------------ #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5

  # Product Specific:


# ------------ Dev Dependencies ------------ #
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# ------------ Assets ------------ #
flutter:
  uses-material-design: true

  # ----------- local assets ------------ #
  assets:
    - assets/icons/
    - assets/videos/
    - assets/images/

  # ----------- local fonts ------------- #
  fonts:
    - family: sans
      fonts:
        - asset: assets/fonts/sans.ttf
          weight: 400
