name: e_store
description: A client e-store app.
publish_to: 'none'
version: 1.0.0-Cinnamon

environment:
  sdk: ">=3.2.0 <4.0.0"

# ------------ Dependencies ------------ #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific:


# ------------ Dev Dependencies ------------ #
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# ------------ Assets ------------ #
flutter:
  uses-material-design: true

  # ----------- local assets ------------ #
  assets:
    - assets/icons/
    - assets/videos/
    - assets/images/

  # ----------- local fonts ------------- #
  fonts:
    - family: sans
      fonts:
        - asset: assets/fonts/sans.ttf
          weight: 400
